# Generated by Django 5.1 on 2024-09-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SignUp_User',
        ),
    ]
